sudo: false

language: node_js

node_js:
  - "6.0"
  - "7.0"
  - "8.0"
  - "9.0"
  - "10.0"
  - "11.0"
  - "12.0"

before_script:
  - npm install -g gulp

script:
  - npm test -- --harmony

after_success:
  - npm run coverage

cache:
  directories:
    - node_modules
